baseURL = "/"
languageCode = "en-us"
title = "ngaih.tech"
theme = "terminal"
paginate = 10
preserveTaxonomyNames = true

[taxonomies]
    category = "categories"

[permalinks]
    post = "/:slug/"
    page = "/:slug/"

[menu]
[[menu.main]]
    identifier = 'home'
    name = 'Home'
    url = '/'
[[menu.main]]
    identifier = 'about'
    name = 'About'
    url = '/about/'
[[menu.main]]
    identifier = 'categories'
    name = 'Categories'
    url = '/categories'

[params]
  contentTypeName = "posts"
  description = "ngaih.tech"
	themeColor = "green"
	fullWidthTheme = false
	centerTheme = true
	favicon = "/android-chrome-512x512.png"

[params.twitter]
    creator = "nga1hte"
    site = "ngaih.tech"

[languages]
  [languages.en]
    title = "ngaih.tech"
    subtitle = "A blog about code and hacking"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "ngaih.tech"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "home"
        name = "Home"
        url = "/"
        weight = 10
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
        weight = 20
      [[languages.en.menu.main]]
        identifier = "categories"
        name = "Categories"
        url = "/categories"
        weight = 30
